version: '3'

services:
    my-postgres-server:
        image: 'postgres'
        environment:
            - POSTGRES_PASSWORD=${PGPASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - /custom/mount:/var/lib/postgresql/data
    my-redis-server:
        image: 'redis'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "8080:80"
    backend:
        depends_on:
            - my-postgres-server
            - my-redis-server
        build: 
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - /opt/app/node_modules
            - ./backend:/opt/app
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PGUSER=${PGUSER}
            - PGHOST=${PGHOST}
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGPORT=${PGPORT}
        restart: always
    frontend:
        build: 
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /opt/app/node_modules
            - ./frontend:/opt/app
        tty: true