apiVersion: v1

kind: Service

metadata:
    name: myapp-service-backend

spec:
  type: NodePort
  ports: 
    - targetPort: 5000
      port: 80
      nodePort: 30011

  selector:
    app: mybackend
    type: backend